// DO NOT EDIT. generated by github.com/tinywasm/orm

package sse

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
)

func (m *SSEMessage) ModelName() string {
	return "ssemessage"
}

var _schemaSSEMessage = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "event", Type: fmt.FieldText},
		{Name: "data", Type: fmt.FieldBlob},
	}

func (m *SSEMessage) Schema() []fmt.Field { return _schemaSSEMessage }

func (m *SSEMessage) Pointers() []any { return []any{&m.ID, &m.Event, &m.Data} }

func (m *SSEMessage) IsNil() bool { return m == nil }

func (m *SSEMessage) EncodeFields(w fmt.FieldWriter) {
	w.String("id", m.ID)
	w.String("event", m.Event)
	w.Bytes("data", m.Data)
}

func (m *SSEMessage) DecodeFields(r fmt.FieldReader) {
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.String("event"); ok { m.Event = v }
	if v, ok := r.Bytes("data"); ok { m.Data = v }
}

type SSEMessageList []*SSEMessage

func (s *SSEMessageList) Schema() []fmt.Field { return nil }
func (s *SSEMessageList) Pointers() []any     { return nil }
func (s *SSEMessageList) Len() int             { return len(*s) }
func (s *SSEMessageList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *SSEMessageList) Append() fmt.Fielder  { v := &SSEMessage{}; *s = append(*s, v); return v }
func (s *SSEMessageList) IsNil() bool          { return s == nil }
func (s *SSEMessageList) EncodeFields(_ fmt.FieldWriter) {}
func (s *SSEMessageList) DecodeFields(_ fmt.FieldReader) {}

func ReadOneSSEMessage(qb *orm.QB, model *SSEMessage) (*SSEMessage, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllSSEMessage(qb *orm.QB) (*SSEMessageList, error) {
	var results SSEMessageList
	err := qb.ReadAll(
		func() fmt.Model { return &SSEMessage{} },
		func(m fmt.Model) { results = append(results, m.(*SSEMessage)) },
	)
	return &results, err
}

